import React, { useState, useEffect, Fragment } from 'react';

import { Loader, Card, FormField, RenderCards } from '../components';

const Home = () => {
	const [loading, setLoading] = useState(false);
	const [allPosts, setAllPosts] = useState(null);
	const [searchText, setSearchText] = useState('');
	const [searchedResults, setSearchedResults] = useState(null);
	const [searchTimeout, setSearchTimeout] = useState(null);

	useEffect(() => {
		const fetchPosts = async () => {
			try {
				setLoading(true);
				const response = await fetch('http://localhost:8080/api/v1/posts');
				const data = await response.json();
				setAllPosts(data.data.reverse());
			} catch (error) {
				console.error(error);
			} finally {
				setLoading(false);
			}
		};

		fetchPosts();
	}, []);

	const handleSearchChange = (e) => {
		clearTimeout(searchTimeout);
		setSearchText(e.target.value);

		setSearchTimeout(
			setTimeout(() => {
				const searchResults = allPosts.filter((post) => post.name.toLowerCase().includes(searchText.toLowerCase()) || post.prompt.toLowerCase().includes(searchText.toLowerCase()));

				setSearchedResults(searchResults);
			}, 500)
		);
	};

	return (
		<section className="max-w-7xl mx-auto">
			<div>
				<h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
				<p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
			</div>

			<div className="mt-16">
				<FormField
					LableName="Search images"
					type="text"
					name="text"
					placeholder="Search images"
					value={searchText}
					handleChange={handleSearchChange}
				/>
			</div>

			<div className="mt-10">
				{loading ? (
					<div className="flex justify-center items-center">
						<Loader />
					</div>
				) : (
					<Fragment>
						{searchText && (
							<h2 className="font-medium text-[#666e75] text-xl mb-3">
								Showing results for <span className="text-[#222328]">{searchText}</span>
							</h2>
						)}
						<div className="grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
							{searchText ? (
								<RenderCards data={searchedResults} title="No search results found" />
							) : (
								<RenderCards data={allPosts} title="No posts found" />
							)}
						</div>
					</Fragment>
				)}
			</div>
		</section>
	)
}

export default Home